version: '3'
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 4000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # env_file:
    #   - .env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=my_fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=1234567890075432123456789
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30

  postgres:
    image: postgres
    environment:
      - POSTRGRES_PASSWORD=postgres
      - POSTRGRES_DB=my_fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
